language: node_js
node_js:
  - 15
  - 14
  - 12

cache:
  npm: false

matrix:
  allow_failures:
    - os: windows

os:
  - linux
  - osx
  - windows

# https://docs.travis-ci.com/user/customizing-the-build/#git-end-of-line-conversion-control
# need for windows
git:
  autocrlf: input


script:
  - npm run lint && npm run build && npm run coverage && npm run report

notifications:
  email:
    on_success: never
    on_failure: change

sudo: required

services:
  - docker

before_deploy:
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
  - sudo service docker start

deploy:
  provider: script
  script: npm run docker-ci
  skip_cleanup: true
  on:
    node: 12
    condition: $TRAVIS_OS_NAME = linux
    tags: true
    all_branches: false
