name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: cloudcmd

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Redrun
        run:
          npm i redrun -g
      
      - name: Install
        run:
          npm install

      - name: Lint
        run:
          redrun fix:lint
    
      - name: Commit fixes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'chore(${{ env.NAME }}) lint using actions'

      - name: Build
        run:
          redrun build

      - name: Test
        run:
          redrun test

      - name: Coverage
        run:
          redrun coverage coverage:report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

